# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dynashard}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Hengeveld"]
  s.date = %q{2011-02-01}
  s.description = %q{Dynashard allows you to shard your ActiveRecord models.  Models can be configured to shard based on context that can be defined dynamically.}
  s.email = %q{nickh@verticalresponse.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "dynashard.gemspec",
    "lib/dynashard.rb",
    "lib/dynashard/associations.rb",
    "lib/dynashard/connection_handler.rb",
    "lib/dynashard/model.rb",
    "lib/dynashard/validations.rb",
    "spec/associations_spec.rb",
    "spec/connection_handler_spec.rb",
    "spec/db/database.yml",
    "spec/db/schema.rb",
    "spec/dynashard_spec.rb",
    "spec/model_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/factories.rb",
    "spec/support/models.rb",
    "spec/validation_spec.rb"
  ]
  s.homepage = %q{http://github.com/nickh/dynashard}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Dynamic sharding for ActiveRecord}
  s.test_files = [
    "spec/associations_spec.rb",
    "spec/connection_handler_spec.rb",
    "spec/db/schema.rb",
    "spec/dynashard_spec.rb",
    "spec/model_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/factories.rb",
    "spec/support/models.rb",
    "spec/validation_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0"])
      s.add_runtime_dependency(%q<arel>, [">= 2.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 3.0"])
      s.add_dependency(%q<arel>, [">= 2.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 3.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 3.0"])
    s.add_dependency(%q<arel>, [">= 2.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 3.0"])
  end
end

